### ISSUE TITLE
load list code 

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#16]
Να δειχνει τα τραγουδια που υπαρχουν και να μπορει ο χρηστης να επιλεξει πιο τραγουδι θα παιζει

**Comment by sotos023** [comment]
Ως δεύτερη εργασία μου είχα να αναπτύξω το load list. Για την συγκεκριμένη εργασία χρειάστηκε να αναπτύξω κώδικα  στην main (για την δημιουργία του κώδικα), στην activity.xml( για το ui ), ενώ χρειάστηκε να δημιουργήσω μια νέα κλάση ,την οποία και ονόμασα Τrackloader η οποία είναι σε java. Η εφαρμογή του load list μας επιτρέπει να βλέπουμε τα τραγούδια που υπάρχουν στην εφαρμογή μας . Τέλος η νέα κλάση TrackLoader είναι υπεύθυνη για τη φόρτωση και την αποθήκευση μιας λίστας τραγουδιών που βρίσκονται στο φάκελο raw μιας εφαρμογής Android. Παρέχει δύο λίστες: μία με τα resource IDs των τραγουδιών και μία με τους τίτλους τους .
