### ISSUE TITLE
seekbar

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#19]
να μπορει ο χρηστης να επιλεγει απο που θελει να ακουσει το τραγουδι

**Comment by sotos023** [comment]
Ως δεύτερη εργασία μου είχα να αναπτύξω το seekbar της εφαρμογής, συγκεκριμένα μόνο τον κώδικά του. Το seekbar είναι η λειτουργία της εφαρμογής όπου επιτρέπει τον χρήστη να τοποθετήσει ,με την βοήθεια του δείκτη, το σημείο του τραγουδιού όπου επιθυμεί ο χρήστης να ακούσει το τραγούδι. Όταν ο χρήστης θελήσει να αλλάξει τραγούδι ή τελειώσει το τραγούδι, ο δείκτης του seekbar επανατοποθετείται στην αρχική του θέση. Τέλος η κλάση στην οποία χρειάστηκε να δουλέψω ήταν μόνο η main.
