### ISSUE TITLE
Ui Καρτελες 

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#20]
tracks/ playlist / artists/ albums. θελω να υλοποιησεις αυτα

**Comment by FELIX6402** [comment]
Θα κανω τα δυνατα μου να τα εχω ολα ετοιμα και λειτουργικα.

**Comment by FELIX6402** [comment]
Τα ui των κατηγοριών υλοποιήθηκαν επιτυχώς. Προχωράω στον προγραμματισμό τους.
