### ISSUE TITLE
ui buttons

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#4]
(play/pause/next/pre)

**Comment by LIAKOSDIA** [comment]
Ανέλαβα και κατέθεσα το UI της εφαρμογής μας. Όπως μπορείτε να δείτε στο κάτω μέρος της οθόνης προσθέσαμε 4 κουμπιά και μια μπάρα. Ένα κουμπί από αυτά είναι το Play με το οποίο ο χρήστης μπορεί να ξεκινήσει να ακούσει το τραγούδι το οποίο έχει επιλέξει. Δίπλα έχουμε τοποθετήσει το κουμπί Pause το οποίο πατώντας ο χρήστης μπορεί να σταματήσει την αναπαραγωγή του τραγουδιού. Μέτα έχουμε δύο τελευταία προς στιγμήν κουμπιά, το Next και το Prev, τα οποία χρησιμεύουν για την αναλλαγή τραγουδιών στο επόμενο και στο προηγούμενο τραγούδι που υπάρχει στην λίστα. Ακριβώς από πάνω υπάρχει μια μπάρα με την οποία μπορούμε να επιλέξουμε την χρονική στιγμή που θέλουμε να ακούσουμε από το επιλεγμένο τραγούδι εκείνη την στιγμή. επιπλέον έχουμε προσθέση προς ώρας μια εικόνα αλλά στη συνέχεια θα απεικονίζει μια εικόνα σχετική με το τραγούδι που ακούει ο χρήστης εκείνη την στιγμή. Πάνω από την εικόνα θα αναγράφεται ο τίτλος και ο καλλιτέχνης του τραγουδιού. Τέλος έχουμε προσθέσει μια μπάρα αναζήτησης η οποία δίνει την δυνατότητα στον χρήστη να αναζητήσει πληκτρολογόντας ένα οποιοδήποτε τραγούδι που υπάρχει στην λίστα του.
