### ISSUE TITLE
tabs 

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#41]
Θέλω να υλοποιήσεις σε tabs/καρτέλες που θα μπορεί ο χρήστης να κάνει περιήγηση στην αναζήτηση/αλμπουμs/αγαπημένα/playlist. Μόνο ui θέλω.

**Comment by FELIX6402** [comment]
Φτιάχτηκαν 4 tabs τα οποία είναι Search, Albums, Favorites και Playlists. Για να φτιαχτούν αυτά εφαρμόσαμε το tablayout στην main. Προστέθηκαν τα Fragments με ονόματα αντίστοιχα των tabs όπως και τα xml αρχεία τους. Δουλειά έγινε στο Search tab όπου εμφανίζεται πρώτο. Μεταφέρθηκε σε αυτό όλος ο κώδικας της main και ο σχεδιασμός της ώστε να δουλεύουν εκεί οι βασικές λειτουργίες της εφαρμογής. Τα υπόλοιπα tabs μένουν άδεια προς το παρόν μέχρι να συζητηθεί από την ομάδα τι λειτουργίες θα έχουν και ποιος θα αναλάβει τον σχεδιασμό και την κωδικοποίησή τους.
