### ISSUE TITLE
Create albums ( charts ) 

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#45]
Δημιουργία στην καρτέλα albums επιλογή charts που θα μπορεί ο χρήστης να βλέπει τα τρέχον charts  ( επέλεξε ότι θες πχ top 50 world)

**Comment by kalan20063** [comment]
Η εργασία που πραγματοποιήθηκε αποσκοπούσε στην ολοκλήρωση μιας πλήρως λειτουργικής οθόνης για την εμφάνιση και αλληλεπίδραση με τα κορυφαία 100 τραγούδια από το Deezer API. Στο πλαίσιο αυτής της διαδικασίας, το UI βελτιώθηκε, και η εφαρμογή επανασχεδιάστηκε για να προσφέρει μια πιο οργανωμένη, καθαρή και εύχρηστη εμπειρία. Η σωστή διαχείριση των δεδομένων, η απόκριση σε σφάλματα και η ομαλή αλληλεπίδραση με τον χρήστη επιτρέπουν στην εφαρμογή να λειτουργεί με έναν φιλικό και αποτελεσματικό τρόπο.

Με την ολοκλήρωση αυτής της εργασίας, η εφαρμογή έχει αναβαθμιστεί τόσο σε επίπεδο λειτουργικότητας όσο και σε επίπεδο εμπειρίας χρήστη, προετοιμάζοντας την για περαιτέρω ανάπτυξη και προσθήκη νέων χαρακτηριστικών.

**Comment by kalan20063** [comment]
Επισης φτιαχτικε 2ο branch για να γινει ενημερωση απο το τωρινο master.
