### ISSUE TITLE
Δημιουργία πληροφοριών καλλιτέχνη 

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#46]
Σε αυτή την λειτουργία ο χρήστης θα πρέπει να μπορεί να πατάει πάνω στον καλλιτέχνη και να βλέπει πληροφορίες σχετικά με αυτόν.

**Comment by sotos023** [comment]
Η εφαρμογή παρέχει μια λειτουργία που επιτρέπει την εύκολη εύρεση πληροφοριών για καλλιτέχνες μέσω αναζήτησης στο διαδίκτυο. Όταν εμφανίζεται η λίστα με τα τραγούδια, μπορείτε να πατήσετε στο όνομα του καλλιτέχνη που σας ενδιαφέρει. Αυτό ενεργοποιεί έναν μηχανισμό που ανοίγει τον προεπιλεγμένο περιηγητή της συσκευής σας και εκτελεί μια αναζήτηση στο Google με το όνομα του καλλιτέχνη. Έτσι, έχετε γρήγορη πρόσβαση σε πληροφορίες, όπως τη βιογραφία, τα δισκογραφικά έργα και ειδήσεις για τον καλλιτέχνη. Η λειτουργία είναι σχεδιασμένη για να διευκολύνει την ανακάλυψη περισσότερων στοιχείων για τη μουσική που σας ενδιαφέρει, ενσωματώνοντας εύχρηστη και άμεση πλοήγηση.
