### ISSUE TITLE
create album (rap)

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#54]
Δημιουργία στην καρτέλα albums επιλογή album (rap)  που θα μπορεί ο χρήστης να βλέπει τα τρέχον rap που το προτείνει.

**Comment by sotos023** [comment]
Η λειτουργία που δημιούργησα επιτρέπει στους χρήστες να βλέπουν μια λίστα τραγουδιών όταν πατούν πάνω στο κουμπί της εικόνας του άλμπουμ. Αφού το πατήσουν, το υποκείμενο FrameLayout με τα τραγούδια εμφανίζεται. Μέσα στο FrameLayout εμφανίζεται ένα RecyclerView με τα τραγούδια, που λαμβάνουν δεδομένα από το Deezer API. Δεν παίζουν τα τραγούδια όταν τα πατάς
