### ISSUE TITLE
create playlist 

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#70]
Η λειτουργία θα επιτρέπει στους χρήστες να δημιουργούν, να αποθηκεύουν και να διαχειρίζονται τα δικά τους playlists, χωρίς περιορισμό στον αριθμό, χρησιμοποιώντας το Firebase για την υλοποίηση. Η εφαρμογή θα προσφέρει δυναμική δημιουργία, επεξεργασία και διαγραφή playlists, διασφαλίζοντας ότι τα δεδομένα είναι συγχρονισμένα και διαθέσιμα σε πραγματικό χρόνο.

**Comment by kalan20063** [comment]
Εχω δημιουργησει τα playlist . Δεν εχει ολοκληρωθει καθως δεν εμφανιζει τα playlist και τα τραγουδια που εχει προσθεσει ο χρηστης μεσα .Μπορει κανονικα να δημιουργησει και να βαλει μεσα τραγουδια.

**Comment by peterkar032** [comment]
το εφτιαξα σε αλλο
