### ISSUE TITLE
play songs on youtube 

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#71]
Η λειτουργία θα επιτρέπει στον χρήστη να παίζει μουσικά βίντεο στο YouTube άμεσα. Όταν ο χρήστης επιλέγει ένα τραγούδι από τα άλμπουμ, τα playlists ή τα αγαπημένα του, η εφαρμογή θα εντοπίζει το αντίστοιχο μουσικό βίντεο στο YouTube και θα το ανοίγει είτε μέσω ενσωματωμένου player στην εφαρμογή είτε κατευθείαν στην πλατφόρμα του YouTube. Η ενσωμάτωση μπορεί να γίνει με τη χρήση του YouTube API για την εύρεση και αναπαραγωγή του κατάλληλου βίντεο.

**Comment by sotos023** [comment]
Αυτή την βδομάδα για την δουλειά μου τροποποίησα την κλάση TrackAdapter, πρόσθεσα η δυνατότητα άμεσης αναζήτησης τραγουδιών στο YouTube μέσω browser, όταν ο χρήστης πατάει τον τίτλο του τραγουδιού. Δημιούργησα ένας σύνδεσμο προς το YouTube και το άνοιγμα γίνεται στον προεπιλεγμένο browser (ή Google Chrome αν είναι εγκατεστημένος). Επιπλέον, προστέθηκε έλεγχος για το αν υπάρχει διαθέσιμος browser για να ανοίξει το URL. Τέλος όποιο τραγούδι από τις κατηγορίες album, favourites παίζει στο youtube όταν το πατάς.
