### ISSUE TITLE
unlike

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#75]
Θα αφαιρεί από τα favorites  τραγούδι που δεν αρέσει στο χρήστη

**Comment by LIAKOSDIA** [comment]
Εχοντας προσθεσει καποιες συναρτησεις στις κλασεις TrackAdapter, Favorites και albums δωσαμε στον χρηστη την λειτουργεια του να μπορει να αφαιρει καποιο τραγουδι απο τα αγαπημενα του.
