### ISSUE TITLE
create playlist v2 

### ISSUE THREAD

**Issue by peterkar032** [peterkar032/music_player-#83]
δεύτερη προσπάθεια 
Η λειτουργία θα επιτρέπει στους χρήστες να δημιουργούν, να αποθηκεύουν και να διαχειρίζονται τα δικά τους playlists, χωρίς περιορισμό στον αριθμό, χρησιμοποιώντας το Firebase για την υλοποίηση. Η εφαρμογή θα προσφέρει δυναμική δημιουργία, επεξεργασία και διαγραφή playlists, διασφαλίζοντας ότι τα δεδομένα είναι συγχρονισμένα και διαθέσιμα σε πραγματικό χρόνο.

**Comment by kalan20063** [comment]
Πλεον ο χρηστης μπορει να εμφανιζει τραγουδια μεσα απο τις Playlist.
